parameters:
    google_geolocation.geolocation_api.class: Google\GeolocationBundle\Geolocation\GeolocationApi
    # Max attempts to Google Geocoding API per day. Google's restriction is 2,500
    google_geolocation.geolocation_api.daily_limit: 10
    # Max lifetime of geocoding result (hours). Set to 0 to disable caching
    google_geolocation.geolocation_api.cache_lifetime: 1
    
services:
    google_geolocation.geolocation_api:
        class:      %google_geolocation.geolocation_api.class%